
spring:
  redis:
    host: redis-12052.c266.us-east-1-3.ec2.redns.redis-cloud.com
    port: 12052
    password: AO7uRA6VzgW5LaBIJfA2A9P8Tj1nsf0x
  data:
    mongodb:
      uri: mongodb+srv://kajukatli995:w0xUkso6at0ZB7UO@cluster0.fxfxuro.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: kajukatli995@gmail.com
    password: dcow htgc lndf beit
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /journal

weather:
  api:
    key: 6b6c446cd7c686b1dc2fb9904a0b71e2

