spring:
  profiles:
    active: dev

logging:
  level:
    restjagdishapi:
      journal:
        app: DEBUG

#logging:
#  level:
#    restjagdishapi:
#      journal:
#        app:
#          service:
#            UserService: OFF
